version: "3.9"

services:
    auth-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: auth-service
        restart: always
        ports:
            - "8080"
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_ADDR=${REDIS_ADDR}
        depends_on:
            - db
            - redis
        networks:
            - app-network

    db:
        image: postgres:16
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB} 
        ports:
            - "5433:5432"
        networks:
            - app-network

    redis:
        image: redis:7
        container_name: redis
        restart: always
        ports:
            - "6380:6379"
        networks:
            - app-network

    migrate:
        image: migrate/migrate
        container_name: migrate
        command:
            [
                "-path",
                "/migrations",
                "-database",
                "${DATABASE_URL}",
                "up",
            ]
        volumes:
            - ./db/migrations:/migrations
        depends_on:
            - db
        networks:
            - app-network

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - auth-service
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
