version: "3.9"

services:
  auth-service:
    build:
      context: .          # build from project root
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    expose:
      - "8080"   # internal only (visible to nginx, not host)
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "80:80"   # external port for App Gateway or public
    depends_on:
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
